### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by minheq** [minheq/grrupwa-boilerplate#1]
**CHECKLIST OF THINGS TO DO**

HMR for server bundle in memory (in future
- [x] production build
- [x] HTML template in js
- [x] Isomorphic relay/react-router
- [x] codesplitting with react router
- [x] PWA - App shell
- [x] PWA - offline
- [ ] PWA - push notifications
- [ ] critical css
- [ ] add AMP support
- [ ] add test-runner
- [ ] bundle optimizations
